all_servers:
  children:
    web_servers:
      hosts:
        web1:
          ansible_host: server1.ironhack.com
          server_type: linux
          ansible_username: root
          ansible_password: Pass@123
          ansible_connection: ssh
          alias: Web Server 1
        web2:  
          ansible_host: server2.ironhack.com
          server_type: linux
          ansible_username: admin
          ansible_password: Pass@123
          ansible_connection: ssh
          alias: Web Server 2
        web3:  
          ansible_host: server3.ironhack.com
          server_type: linux
          ansible_username: root
          ansible_password: pass
          ansible_connection: ssh
          alias: Web Server 3
          
    db_servers:
      hosts:
        db1:
          ansible_host: db1.ironhack.com
          server_type: window
          ansible_username: admin
          ansible_password: Pass@123
          alias: DB Server
          ansible_connection: winrm
local:
  hosts:
    localhost:
      server_type: linux
      alias: Control Server
      ansible_connection: local 
      ansible_username: null
      ansible_password: null
