- name: Create a standalone Apache server
  hosts: all
  become: yes
  vars:
    doc_root: /var/www/example
  tasks:
    - name: Update apt
      apt: update_cache=yes

    - name: Install Apache
      apt: name=apache2 state=latest

    - name: Create custom document root
      file: path={{ doc_root }} state=directory owner=www-data group=www-data
 
    #add new index.html in /var/www/example directory
    - name: Set up HTML file
      copy: src=index.html dest={{ doc_root }}/index.html owner=www-data group=www-data mode=0644
 
    #link new configurations!
    - name: Set up Apache virtual host file
      template: src=vhosts.tpl dest=/etc/apache2/sites-available/000-default.conf
      notify: restart apache
 
 #Handlers are like triggers; they execute only when the service-defined changes.
  handlers:
    - name: restart apache
      service: name=apache2 state=restarted