- name: Install Apache
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  become: true

- name: Configure load balancer virtual host
  template:
    src: ../templates/000-default.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
    mode: 0755
  notify: Restart Apache
  become: true

- name: Enable mod_proxy
  ansible.builtin.command: a2enmod proxy
  become: true
  notify: Restart Apache

- name: Enable mod_proxy_http
  ansible.builtin.command: a2enmod proxy_http
  become: true
  notify: Restart Apache

 
- name: Enable mod_proxy_balancer
  ansible.builtin.command: a2enmod proxy_balancer
  become: true
  notify: Restart Apache

- name: Enable lbmethod_byrequests
  ansible.builtin.command: a2enmod lbmethod_byrequests
  become: true
  notify: Restart Apache







